FROM node:20-alpine AS builder

WORKDIR /app

COPY ./Frontend/package.json ./

RUN npm install

COPY ./Frontend .

RUN npm run build

# --- Production-Stage ---
FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]