name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Backend - Install Dependencies
      run: npm install
      working-directory: ./Backend

    - name: Backend - Run Tests
      run: npm run test
      working-directory: ./Backend
      env:
        NODE_ENV: test

    - name: Frontend - Install Dependencies
      run: npm install
      working-directory: ./Frontend

    - name: Frontend - Build Project
      run: npm run build
      working-directory: ./Frontend
      env:
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        publish_dir: ./Frontend/build
